# Generated by Django 5.1.1 on 2024-09-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('on_loan', models.BooleanField(default=False)),
                ('holder', models.CharField(max_length=100)),
                ('expected_return_date', models.DateField()),
            ],
        ),
    ]
