# Generated by Django 5.1.1 on 2024-09-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vip_number', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=100)),
                ('loan_length', models.IntegerField(help_text='Duration in days')),
                ('earliest_start_date', models.DateField()),
                ('contact_detail', models.CharField(max_length=100)),
            ],
        ),
    ]
