# Generated by Django 5.1.1 on 2024-09-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('vip_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('capture_date', models.DateField()),
                ('capture_time', models.TimeField()),
                ('IOP_OD_left', models.IntegerField()),
                ('IOP_OD_right', models.IntegerField()),
                ('position', models.IntegerField()),
                ('contact_detail', models.CharField(max_length=100)),
            ],
        ),
    ]
