# Generated by Django 5.1.1 on 2024-09-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0003_reservationdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdata',
            old_name='IOP_OD_right',
            new_name='IOP_OS_right',
        ),
        migrations.RemoveField(
            model_name='reservationdata',
            name='contact_detail',
        ),
    ]
