# Generated by Django 5.1.1 on 2024-09-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0005_alter_reservationdata_iop_od_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='vip_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservationdata',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservationdata',
            name='vip_number',
            field=models.CharField(max_length=50),
        ),
    ]
